/**
 * ============================================================
 * OMEN PROTOCOL — Phase 4: zkLogin AI Agent
 * ============================================================
 * The AI auditing agent authenticates via OpenID Connect (OIDC),
 * derives its sovereign Sui wallet address using zkLogin,
 * and submits the verify_and_update_badge transaction without
 * ever hardcoding a raw private key on the server.
 *
 * Prerequisites:
 *   - A Google OAuth 2.0 client ID configured for service account use
 *   - The ZK proof generated by Phase 3 (snarkjs / ark-circom)
 *   - The Walrus blob ID from Phase 2
 *   - The registry object ID and badge object ID from the Move contract
 * ============================================================
 */

import {
  SuiClient,
  getFullnodeUrl,
  SuiTransactionBlockResponse,
} from "@mysten/sui/client";
import { Transaction } from "@mysten/sui/transactions";
import { Ed25519Keypair } from "@mysten/sui/keypairs/ed25519";
import {
  generateNonce,
  generateRandomness,
  getExtendedEphemeralPublicKey,
  jwtToAddress,
  getZkLoginSignature,
  ZkLoginPublicIdentifier,
} from "@mysten/sui/zklogin";
import { jwtDecode } from "jwt-decode";

// ---------------------------------------------------------------------------
// Configuration — inject via environment variables
// ---------------------------------------------------------------------------

const NETWORK = (process.env.SUI_NETWORK ?? "testnet") as
  | "mainnet"
  | "testnet"
  | "devnet";

const REGISTRY_OBJECT_ID = process.env.OMEN_REGISTRY_ID!;
const PACKAGE_ID = process.env.OMEN_PACKAGE_ID!;
const PROVER_URL =
  process.env.ZK_PROVER_URL ?? "https://prover-dev.mystenlabs.com/v1";
const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID!;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface ZkLoginSession {
  ephemeralKeypair: Ed25519Keypair;
  randomness: string;
  nonce: string;
  maxEpoch: number;
}

interface ZkProofBundle {
  proofPoints: {
    a: string[];
    b: string[][];
    c: string[];
  };
  issBase64Details: {
    indexMod4: number;
    value: string;
  };
  headerBase64: string;
}

// ---------------------------------------------------------------------------
// Step 1: Generate ephemeral keypair and nonce for OIDC auth
// ---------------------------------------------------------------------------

export async function createZkLoginSession(): Promise<ZkLoginSession> {
  const client = new SuiClient({ url: getFullnodeUrl(NETWORK) });

  // Get current epoch so we can set maxEpoch = current + 2
  const { epoch } = await client.getLatestSuiSystemState();
  const maxEpoch = Number(epoch) + 2;

  const ephemeralKeypair = new Ed25519Keypair();
  const randomness = generateRandomness();
  const nonce = generateNonce(
    ephemeralKeypair.getPublicKey(),
    maxEpoch,
    randomness
  );

  console.log(`[zkLogin] Session created.`);
  console.log(`          Max Epoch : ${maxEpoch}`);
  console.log(`          Nonce     : ${nonce}`);
  console.log(
    `[zkLogin] Use this nonce in your OIDC authorization URL as &nonce=${nonce}`
  );

  return { ephemeralKeypair, randomness, nonce, maxEpoch };
}

// ---------------------------------------------------------------------------
// Step 2: Exchange JWT from OIDC provider for a ZK proof
// ---------------------------------------------------------------------------
// In a headless service account setup, the JWT is obtained via Google's
// service account flow or a custom internal OIDC provider.
// ---------------------------------------------------------------------------

export async function fetchZkProof(
  jwt: string,
  session: ZkLoginSession,
  userSalt: string // deterministic salt — store securely, never changes
): Promise<{ proof: ZkProofBundle; userAddress: string }> {
  const decodedJwt = jwtDecode<{ sub: string; iss: string; aud: string }>(jwt);
  console.log(
    `[zkLogin] JWT decoded. Subject: ${decodedJwt.sub}, Issuer: ${decodedJwt.iss}`
  );

  // Derive the AI agent's deterministic on-chain address
  const userAddress = jwtToAddress(jwt, userSalt);
  console.log(`[zkLogin] AI Agent Sui Address: ${userAddress}`);

  // Request ZK proof from the Mysten Labs prover service
  // (or your self-hosted prover in production)
  const extendedEphemeralPublicKey = getExtendedEphemeralPublicKey(
    session.ephemeralKeypair.getPublicKey()
  );

  console.log(`[zkLogin] Requesting ZK proof from prover...`);
  const proofResponse = await fetch(PROVER_URL, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      jwt,
      extendedEphemeralPublicKey,
      maxEpoch: session.maxEpoch,
      jwtRandomness: session.randomness,
      salt: userSalt,
      keyClaimName: "sub",
    }),
  });

  if (!proofResponse.ok) {
    throw new Error(
      `ZK prover failed (HTTP ${proofResponse.status}): ${await proofResponse.text()}`
    );
  }

  const proof = (await proofResponse.json()) as ZkProofBundle;
  console.log(`[zkLogin] ✅ ZK proof obtained.`);

  return { proof, userAddress };
}

// ---------------------------------------------------------------------------
// Step 3: Build and submit the verify_and_update_badge transaction
// ---------------------------------------------------------------------------

export interface BadgeUpdateParams {
  badgeObjectId: string;
  clockObjectId: string;
  publicInputsBytes: number[];  // risk_score as little-endian field element
  proofPointsBytes: number[];   // serialized Groth16 proof (A, B, C)
  blobId: string;               // Walrus blob ID from Phase 2
  riskScore: number;            // plain integer for the Move u64 param
}

export async function submitBadgeUpdate(
  session: ZkLoginSession,
  zkProof: ZkProofBundle,
  userAddress: string,
  userSalt: string,
  jwt: string,
  params: BadgeUpdateParams
): Promise<SuiTransactionBlockResponse> {
  const client = new SuiClient({ url: getFullnodeUrl(NETWORK) });

  console.log(`[zkLogin] Building verify_and_update_badge transaction...`);

  const tx = new Transaction();

  tx.moveCall({
    target: `${PACKAGE_ID}::omen_registry::verify_and_update_badge`,
    arguments: [
      tx.object(REGISTRY_OBJECT_ID),          // registry: &OmenRegistry
      tx.object("0x6"),                        // clock: &Clock (Sui system clock)
      tx.object(params.badgeObjectId),         // badge: &mut OmenBadge
      tx.pure.vector("u8", params.publicInputsBytes),
      tx.pure.vector("u8", params.proofPointsBytes),
      tx.pure.string(params.blobId),
      tx.pure.u64(params.riskScore),
    ],
  });

  tx.setSender(userAddress);

  const { bytes, signature: ephemeralSignature } =
    await tx.sign({ signer: session.ephemeralKeypair, client });

  // Assemble the zkLogin signature from the ZK proof + ephemeral sig
  const zkLoginSignature = getZkLoginSignature({
    inputs: {
      ...zkProof,
      addressSeed: userSalt,
    },
    maxEpoch: session.maxEpoch,
    userSignature: ephemeralSignature,
  });

  console.log(`[zkLogin] Submitting transaction to ${NETWORK}...`);

  const result = await client.executeTransactionBlock({
    transactionBlock: bytes,
    signature: zkLoginSignature,
    options: { showEffects: true, showEvents: true },
  });

  if (result.effects?.status?.status !== "success") {
    throw new Error(
      `Transaction failed: ${JSON.stringify(result.effects?.status)}`
    );
  }

  console.log(`[zkLogin] ✅ Badge updated on-chain.`);
  console.log(`          Digest: ${result.digest}`);

  return result;
}

// ---------------------------------------------------------------------------
// Convenience: Full pipeline — session → proof → tx (for testing)
// ---------------------------------------------------------------------------
// In production, createZkLoginSession() runs once, the nonce is embedded
// in the OIDC redirect, the JWT is obtained server-side, and then
// fetchZkProof + submitBadgeUpdate are called per audit cycle.
// ---------------------------------------------------------------------------

export async function runAgentPipeline(
  jwt: string,
  userSalt: string,
  params: BadgeUpdateParams
): Promise<void> {
  const session = await createZkLoginSession();
  const { proof, userAddress } = await fetchZkProof(jwt, session, userSalt);
  const result = await submitBadgeUpdate(
    session,
    proof,
    userAddress,
    userSalt,
    jwt,
    params
  );
  console.log(`[Agent] Pipeline complete. Tx digest: ${result.digest}`);
}
